
#https://qiita.com/tatsurou313/items/ad86da1bb9e8e570b6fa
# using external cache
# $ docker buildx build --cache-from type=registry,ref=ryu310/github_action_sandbox .
# $ docker buildx bake -f docker-compose.yml

version: '3'
services:
## copy db_llama replace ##   vecdb:
## copy db_llama replace ##     build:
## copy db_llama replace ##       context: python
## copy db_llama replace ##       dockerfile: Dockerfile-vecdb
## copy db_llama replace ##     image: kazuhayase/study:da_elyza_vecdb
## copy db_llama replace ##     secrets:
## copy db_llama replace ##       - .env
## copy db_llama replace ##     tty: true
## copy db_llama replace ##     volumes:
## copy db_llama replace ##       - /home/${USER:?check USER}:/root/_home:ro    

  fapi:
    build:
      context: python
#impossible#      secrets: .env
    image: kazuhayase/study:da_elyza_fapi
    secrets:
      - .env
    tty: true
    volumes:
      - /home/${USER:?check USER}:/root/_home:ro    
    ports:
      - "9000:9000"

  react:
    build: javascript
    depends_on:
      - fapi
    image: kazuhayase/study:da_elyza_react
    tty: true
    ports:
      - "3000:3000"

secrets:
  .env:
   file: /home/${USER:?check USER}/.env
