
#https://qiita.com/tatsurou313/items/ad86da1bb9e8e570b6fa
# using external cache
# $ docker buildx build --cache-from type=registry,ref=ryu310/github_action_sandbox .
# $ docker buildx bake -f docker-compose.yml

version: '3'
services:
  fapi:
    build: python
    image: kazuhayase/study:da_elyza_fapi
    tty: true
#    environment:
#      - OPENAI_BASE_URL="${OPENAI_BASE_URL:-https://api.openai.com/v1}"
#      - OPENAI_API_KEY=${OPENAI_API_KEY:?review .env}
#      - ELYZA_BASE_URL=${ELYZA_BASE_URL:-https://api.platform.elyza.ai/v2}"
#      - ELYZA_API_KEY=${ELYZA_API_KEY:?review .env}
    volumes:
      - /home/${USER:?review.env}:/root/_home:ro
    ports:
      - "9000:9000"

  react:
    build: javascript
    image: kazuhayase/study:da_elyza_react
    tty: true
    ports:
      - "3000:3000"
